export interface User {
    userId: number | null;
    name: string | null;
    phone: string | null;
    email: string | null;
    age: number | null;
    gender: string | null;
    netflix: number | null;
    amazonPrime: number | null;
    disney: number | null;
    paramount: number | null;
    max: number | null;
    hulu: number | null;
    appleTv: number | null;
    peacock: number | null;
    city: string | null;
    state: string | null;
    zip: number | null;
}